### ISSUE TITLE
Arquivos css e js não encontrados

### ISSUE THREAD

**Issue by rodrigocamposdf** [eDemocracia/edemocracia#104]
Subi o e-Democracia localmente e ao carregar a página inicial me deparo com muitas quebras de estilo devido a ausência de alguns arquivos css e js. 

Parece que não localiza nenhum arquivo que está dentro de http://127.0.0.1:8000/static/CACHE/*

Como corrigir esse problema?

![image](https://user-images.githubusercontent.com/32779262/93892828-5601c400-fcc3-11ea-8e3c-6ab5e9edfe89.png)

**Comment by erivanio** [comment]
Bom dia, você subiu com o docker? Como está o serviço do nginx no docker-compose?

**Comment by rodcamp** [comment]
Boa tarde. Eu acabei descobrindo que o NGINX é uma dependência para subir a aplicação e que o e-Democracia por si próprio não consegue localizar os arquivos css e js. O problema foi resolvido após a inclusão do NGINX.
