### ISSUE TITLE
Os parâmetros SITE_LOGO e SITE_NAME só funcionam com o módulo discourse habilitado, mesmo na versão 1.4

### ISSUE THREAD

**Issue by rodrigocamposdf** [eDemocracia/edemocracia#106]
Estou usando a versão **1.4** onde tem a nova funcionalidade **DISCOURSE_ENABLED="False"**.

Ao subir com essa opção, os parâmetros **SITE_LOGO** e **SITE_NAME** são ignorados...

![image](https://user-images.githubusercontent.com/32779262/94098663-82225f80-fdff-11ea-87b6-4104e338c3f6.png)

**Comment by rodcamp** [comment]
Consegui contornar o problema customizando a imagem 1.2.0 com o arquivo **runserver-production** da versão 1.4.0
